modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"


# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues"

[[mods]]
modId = "kjspncr"
version = "${version}"
displayName = "KubeJS PneumaticCraft"
logoFile="icon.png"
# credits="Thanks to FooterMan for the KubeJS Addon Template!"
authors="FooterMan!"
description = '''
KubeJS Addon for PneumaticCraft support.
'''

[[dependencies.kjspncr]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kjspncr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kjspncr]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"
